name: gsoc_harmon_2025
channels:
- pytorch
- conda-forge
- defaults
dependencies:
- appnope=0.1.4
- asttokens=2.4.1
- blas=1.0
- brotli=1.0.9
- brotli-bin=1.0.9
- bzip2=1.0.8
- charset-normalizer=2.0.4
- comm=0.2.2
- cycler=0.11.0
- dataclasses=0.8
- decorator=5.1.1
- exceptiongroup=1.2.0
- executing=2.0.1
- expat=2.5.0
- fonttools=4.25.0
- freetype=2.12.1
- huggingface_hub=0.22.1
- importlib_metadata=7.1.0
- ipykernel=6.29.3
- jedi=0.19.1
- jpeg=9e
- jupyter_client=8.6.1
- lcms2=2.12
- lerc=3.0
- libbrotlicommon=1.0.9
- libbrotlidec=1.0.9
- libbrotlienc=1.0.9
- libcxx=14.0.6
- libdeflate=1.17
- libgfortran5=11.3.0
- libjpeg-turbo=2.0.0
- libopenblas=0.3.21
- libpng=1.6.39
- libsodium=1.0.18
- libtiff=4.5.1
- libwebp-base=1.3.2
- llvm-openmp=14.0.6
- lz4-c=1.9.4
- matplotlib-inline=0.1.6
- munkres=1.1.4
- ncurses=6.4
- nest-asyncio=1.6.0
- nltk=3.8.1
- openjpeg=2.3.0
- openssl=3.0.13
- parso=0.8.3
- pexpect=4.9.0
- pickleshare=0.7.5
- platformdirs=4.2.0
- prompt-toolkit=3.0.42
- ptyprocess=0.7.0
- pure_eval=0.2.2
- pygments=2.17.2
- python=3.12.2
- python-dateutil=2.8.2
- python-tzdata=2023.3
- pytorch=2.2.2
- readline=8.2
- sacremoses=0.0.43
- sentence-transformers=2.6.1
- six=1.16.0
- sqlite=3.41.2
- stack_data=0.6.2
- threadpoolctl=3.4.0
- tk=8.6.12
- traitlets=5.14.2
- tzdata=2024a
- wcwidth=0.2.13
- xz=5.4.6
- yaml=0.2.5
- zeromq=4.3.5
- zipp=3.17.0
- zlib=1.2.13
- zstd=1.5.5
- pip
- pip:
  - aiofiles==23.2.1
  - aiohttp==3.9.5
  - aiosignal==1.3.1
  - alabaster==0.7.16
  - altair==5.3.0
  - annotated-types==0.7.0
  - anthropic==0.14.0
  - anyio==4.4.0
  - appdirs==1.4.4
  - argparse==1.4.0
  - arrow==1.3.0
  - asgiref==3.8.1
  - attrs==23.2.0
  - babel==2.16.0
  - backcall==0.2.0
  - backoff==2.2.1
  - bcrypt==4.1.3
  - beautifulsoup4==4.12.3
  - bioregistry==0.11.12
  - bleach==6.1.0
  - blinker==1.8.2
  - blis==0.7.11
  - bravado==11.0.3
  - bravado-core==6.1.1
  - bs4==0.0.2
  - build==1.2.1
  - cachetools==5.3.3
  - catalogue==2.0.10
  - cbio-py==0.1.4
  - chroma-hnswlib==0.7.3
  - chromadb==0.5.3
  - class-resolver==0.4.3
  - cloudpathlib==0.18.1
  - cohere==4.45
  - coloredlogs==15.0.1
  - confection==0.1.5
  - coverage==7.5.4
  - curies==0.7.10
  - cymem==2.0.8
  - dataclasses-json==0.6.7
  - datasets>=2.18.0
  - defusedxml==0.7.1
  - deprecated==1.2.14
  - dill==0.3.8
  - distro==1.9.0
  - dnspython==2.6.1
  - docopt==0.6.2
  - email-validator==2.2.0
  - fastapi==0.111.0
  - fastapi-cli==0.0.4
  - fastavro==1.9.4
  - fastjsonschema==2.20.0
  - ffmpy==0.3.2
  - flatbuffers==24.3.25
  - fqdn==1.5.1
  - frozenlist==1.4.1
  - fsspec==2023.10.0
  - fuzzywuzzy==0.18.0
  - gensim==4.3.3
  - gitdb==4.0.11
  - gitpython==3.1.43
  - google-auth==2.30.0
  - googleapis-common-protos==1.63.1
  - gpt4all==2.7.0
  - gradio==4.37.2
  - gradio-client==1.0.2
  - grpcio==1.64.1
  - h11==0.14.0
  - httpcore==1.0.5
  - httptools==0.6.1
  - httpx==0.27.0
  - humanfriendly==10.0
  - imagesize==1.4.1
  - importlib-metadata==6.11.0
  - importlib-resources==6.4.0
  - iniconfig==2.0.0
  - ipython==8.12.3
  - isoduration==20.11.0
  - jaraco-classes==3.4.0
  - jaraco-context==5.3.0
  - jaraco-functools==4.0.2
  - jsonlines==4.0.0
  - jsonpatch==1.33
  - jsonpointer==2.4
  - jsonref==1.1.0
  - jsonschema==4.22.0
  - jsonschema-specifications==2023.12.1
  - jupyterlab-pygments==0.3.0
  - keyring==25.3.0
  - kubernetes==30.1.0
  - langchain==0.2.7
  - langchain-chroma==0.1.2
  - langchain-community==0.2.7
  - langchain-core==0.2.12
  - langchain-nomic==0.1.2
  - langchain-openai==0.1.14
  - langchain-text-splitters==0.2.1
  - langchainhub==0.1.20
  - langcodes==3.4.0
  - langgraph==0.1.1
  - langsmith==0.1.81
  - language-data==1.2.0
  - loguru==0.7.2
  - lxml==5.2.2
  - marisa-trie==1.2.0
  - markdown-it-py==3.0.0
  - marshmallow==3.21.3
  - mdit-py-plugins==0.4.1
  - mdurl==0.1.2
  - mistune==3.0.2
  - mmh3==4.1.0
  - monotonic==1.6
  - more-click==0.1.2
  - more-itertools==10.4.0
  - msgpack==1.0.8
  - multidict==6.0.5
  - multiprocess==0.70.16
  - murmurhash==1.0.10
  - mypy-extensions==1.0.0
  - nbclient==0.10.0
  - nbconvert==7.16.4
  - nbformat==5.10.4
  - neo4j==5.20.0
  - nh3==0.2.18
  - nomic==3.0.33
  - oauthlib==3.2.2
  - ols-client==0.1.4
  - onnxruntime==1.18.0
  - openai==1.35.3
  - opentelemetry-api==1.25.0
  - opentelemetry-exporter-otlp-proto-common==1.25.0
  - opentelemetry-exporter-otlp-proto-grpc==1.25.0
  - opentelemetry-instrumentation==0.46b0
  - opentelemetry-instrumentation-asgi==0.46b0
  - opentelemetry-instrumentation-fastapi==0.46b0
  - opentelemetry-proto==1.25.0
  - opentelemetry-sdk==1.25.0
  - opentelemetry-semantic-conventions==0.46b0
  - opentelemetry-util-http==0.46b0
  - orjson==3.10.5
  - overrides==7.7.0
  - owlready2==0.46
  - packaging==23.2
  - pandas==2.2.2
  - pandocfilters==1.5.1
  - pathos==0.3.2
  - pillow==10.3.0
  - pinecone-client==3.1.0
  - pinecone-plugin-interface==0.0.7
  - pip==24.2
  - pipreqs==0.5.0
  - pkginfo==1.10.0
  - pluggy==1.5.0
  - posthog==3.5.0
  - pox==0.3.4
  - ppft==1.7.6.8
  - preshed==3.0.9
  - protobuf==4.25.3
  - pubmed-parser==0.4.0
  - pyarrow==16.1.0
  - pyarrow-hotfix==0.6
  - pyasn1==0.6.0
  - pyasn1-modules==0.4.0
  - pydantic==2.7.4
  - pydantic-core==2.18.4
  - pydeck==0.9.1
  - pydub==0.25.1
  - pyjwt==2.8.0
  - pymongo==4.8.0
  - pypdf==4.2.0
  - pypika==0.48.9
  - pyproject-hooks==1.1.0
  - pysbd==0.3.4
  - pystow==0.5.4
  - pytest==8.2.2
  - pytest-cov==5.0.0
  - python-dotenv==1.0.1
  - python-multipart==0.0.9
  - pytrie==0.4.0
  - ragas==0.1.0
  - rapidfuzz==3.9.6
  - readme-renderer==43.0
  - referencing==0.35.1
  - requests==2.32.3
  - requests-oauthlib==2.0.0
  - requests-toolbelt==1.0.0
  - rfc3339-validator==0.1.4
  - rfc3986==2.0.0
  - rfc3986-validator==0.1.1
  - rich==13.7.1
  - rpds-py==0.18.1
  - rsa==4.9
  - ruff==0.5.1
  - safetensors==0.4.2
  - scikit-learn==1.5.1
  - semantic-version==2.10.0
  - setuptools==70.2.0
  - shellingham==1.5.4
  - shortuuid==1.0.13
  - simplejson==3.19.2
  - smart-open==7.0.4
  - smmap==5.0.1
  - sniffio==1.3.1
  - snowballstemmer==2.2.0
  - sortedcontainers==2.4.0
  - soupsieve==2.5
  - spacy-legacy==3.0.12
  - spacy-loggers==1.0.5
  - sparse-dot-topn==1.1.3
  - sphinx==7.4.7
  - sphinxcontrib-applehelp==2.0.0
  - sphinxcontrib-devhelp==2.0.0
  - sphinxcontrib-htmlhelp==2.1.0
  - sphinxcontrib-jsmath==1.0.1
  - sphinxcontrib-qthelp==2.0.0
  - sphinxcontrib-serializinghtml==2.0.0
  - sqlalchemy==2.0.31
  - srsly==2.4.8
  - starlette==0.37.2
  - streamlit==1.37.0
  - swagger-spec-validator==3.0.3
  - tavily-python==0.3.3
  - tenacity==8.4.1
  - text2term==4.2.1
  - thefuzz==0.22.1
  - thinc==8.2.5
  - tiktoken==0.7.0
  - tinycss2==1.3.0
  - tokenizers==0.15.2
  - toml==0.10.2
  - tomlkit==0.12.0
  - toolz==0.12.1
  - tqdm==4.66.5
  - transformers==4.39.2
  - twine==5.1.1
  - typer==0.12.3
  - types-python-dateutil==2.9.0.20240316
  - types-requests==2.32.0.20240622
  - typing-inspect==0.9.0
  - ujson==5.10.0
  - unidecode==1.3.8
  - uri-template==1.3.0
  - uvicorn==0.30.1
  - uvloop==0.19.0
  - wasabi==1.1.3
  - watchfiles==0.22.0
  - weasel==0.4.1
  - webcolors==1.13
  - webencodings==0.5.1
  - websocket-client==1.8.0
  - websockets==11.0.3
  - wrapt==1.16.0
  - xxhash==3.4.1
  - yarg==0.1.9
  - yarl==1.9.4
